src/app.py
from sys import prefix
from flask import Flask

app = Flask(__name__)

#ROUTES
from routes.index import index
app.register_blueprint(index)

if __name__ == "__main__":
    app.run(debug=True)

src/routes/index.py
from flask import Blueprint, jsonify, redirect, render_template, request, url_for, Response
from triggers import TriggerGame, TriggerOffers

index = Blueprint('index', __name__)

@index.route('/')
def get_index():
    return render_template('index.html')

@index.route('/juego', methods=["POST"])
def get_juego():
    scrape = TriggerGame()
    result = scrape.parse_data(request.form.get('game-link'))
    return jsonify(result)

@index.route('/ofertas')
def get_ofertas_page():
    return render_template('ofertas.html')

@index.route('/ofertas', methods=['POST'])
def get_ofertas():
    scrape = TriggerOffers()
    result = scrape.parse_data()
    return jsonify(result)

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    <link rel="stylesheet" href="/static/css/index.css">
    <link rel="stylesheet" href="/static/css/responsive.css">
    <link rel="shortcut icon" href="/static/img/favicon.ico" type="image/x-icon">
    <title>{% block title %} {% endblock %}</title>
    {% endblock %}
</head>
<body>
    {% include 'partials/header.html' %}

    <!-- CONTENT -->
    <main>
        {% block main %} {% endblock %}
    </main>

    {% include 'partials/footer.html' %}

    {% block scripts %} {% endblock %}
</body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{% block title %} Comparación de precios {% endblock %}

{% block main %}
<h1 class="mb-3 text-light">Obtener precios de un juego</h1>
<form onsubmit="getGame(event)" method="post" class="form-game">
    <span>
        <input type="text" name="game-link" id="game" class="form-control shadow-none" placeholder="Nombre del juego"
            autocomplete="off">
    </span>
    <button class="btn material-symbols-outlined search-btn"> search </button>
</form>

<div class="modal modal-xl fade" id="modalJuegos" tabindex="-1" aria-labelledby="modalJuegosLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h1 class="modal-title w-100 text-center" id="modalJuegosTitle">Juego</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="loading w-100 text-center">
                    <div class="spinner-border" role="status">
                        <span class="visually-hidden">Loading...</span>
                    </div>
                </div>
            </div>
            <div class="modal-footer border-0">
                <button type="button" class="btn btn-success w-100" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

<template id="juegoTemplate">
    <div class="container-juego">
        <img src="" alt="cover">
        <div class="container-descripcion">
            <h2 class="titulo"> titulo </h2>
            <p class="descripcion"> descripcion </p>
        </div>
    </div>

    <h3 class="text-center mt-4 mb-2">Plataformas</h3>
    <div class="plataformas">
        <div class="steam">
            <div class="info">
                <img src="{{url_for('static', filename='img/steam.png')}}" alt="">
                <p> Precio: <span class="precio"> 15$ </span></p>
                <p> Descuento: <span class="descuento"> 50% </span></p>
                <p> Precio final: <span class="final"> 7.5$ </span></p>
            </div>
            <a href="#" target="_blank" class="btn btn-dark">Ir</a>
        </div>

        <div class="gog">
            <div class="info">
                <img src="{{url_for('static', filename='img/gog.png')}}" alt="">
                <p> Precio: <span class="precio"> 15$ </span></p>
                <p> Descuento: <span class="descuento"> 50% </span></p>
                <p> Precio final: <span class="final"> 7.5$ </span></p>
            </div>

            <a href="#" target="_blank" class="btn btn-dark">Ir</a>
        </div>

        <div class="egs">
            <div class="info">
                <img src="{{url_for('static', filename='img/egs.png')}}" alt="">
                <p> Precio: <span class="precio"> 15$ </span></p>
                <p> Descuento: <span class="descuento"> 50% </span></p>
                <p> Precio final: <span class="final"> 7.5$ </span></p>
            </div>
            <a href="#" target="_blank" class="btn btn-dark">Ir</a>
        </div>
    </div>
</template>

{% endblock %}

{% block scripts %}
<script>
    // EFFECT FOR INPUT TEXT
    const input = document.querySelector('.form-game #game');
    input.addEventListener('focusin', (event) => {
        document.documentElement.style.setProperty('--input-width', '100%');
    });

    input.addEventListener('focusout', (event) => {
        document.documentElement.style.setProperty('--input-width', '0%');
    });

    // SUBMIT FORM
    const templateJuego = document.querySelector('#juegoTemplate').content;
    const modalContent = document.querySelector('#modalJuegos .modal-body');

    addEventListener('hidden.bs.modal', () => {
        modalContent.innerHTML = "<div class='loading w-100 text-center'><div class='spinner-border' role='status'><span class='visually-hidden'>Loading...</span></div></div>";
    })

    const getGame = async (evt) => {
        // ACTIVATE MODAL
        const modal = new bootstrap.Modal(document.querySelector('#modalJuegos'));
        modal.show()

        // SEARCH DATA
        evt.preventDefault()
        const form = new FormData(document.querySelector('.form-game'));
        const res = await fetch('/juego', {
            method: 'POST',
            body: form,
        });
        const data = await res.json()

        // INFO STEAM
        console.log(data);
        const clone = templateJuego.cloneNode(true);
        if (data.steam !== null) {
            clone.querySelector('.titulo').innerHTML = data.steam.nombre;
            clone.querySelector('.descripcion').innerHTML = data.steam.descripcion;
            clone.querySelector('img').src = data.steam.img;
            clone.querySelector('img').style.minHeight = '200px';

            // PRECIOS
            clone.querySelector('.steam .precio').innerText = `${data.steam.precio}$`;
            if (data.steam.descuento !== null){
                const porcentaje = 100 - ((data.steam.descuento * 100) / data.steam.precio);
                clone.querySelector('.steam .descuento').innerText = `${porcentaje.toFixed(2)}%`
            } else{
                clone.querySelector('.steam .descuento').innerText = 'Ninguno';
                clone.querySelector('.steam .final').innerText = `${data.steam.precio}$`;
            }
            
            clone.querySelector('.steam a').href = data.steam.link
        } else {
            clone.querySelector('.steam').remove();
        }

        const titulo = clone.querySelector('.titulo').innerText.trim()
        // INFO EGS
        if (data.egs !== null) {
            clone.querySelector('.titulo').innerHTML = data.egs.nombre;

            // VERIFICAR DESCRIPCION
            if (clone.querySelector('.descripcion').innerText.trim() === 'descripcion') {
                clone.querySelector('.descripcion').innerHTML = data.egs.descripcion;
            }

            // VERIFICAR COVER
            if (clone.querySelector('img').src === ''){
                clone.querySelector('img').src = data.egs.img;
                clone.querySelector('img').style.minHeight = '300px';
            }

            // PRECIOS
            clone.querySelector('.egs .precio').innerText = `${data.egs.precio}$`;
            if (data.egs.descuento !== null){
                const porcentaje = 100 - ((data.egs.descuento * 100) / data.egs.precio);
                clone.querySelector('.egs .descuento').innerText = `${porcentaje.toFixed(2)}%`
                clone.querySelector('.egs .final').innerText = `${data.egs.descuento}$`;
            } else{
                clone.querySelector('.egs .descuento').innerText = 'Ninguno';
                clone.querySelector('.egs .final').innerText = `${data.egs.precio}$`;
            }

            clone.querySelector('.egs a').href = data.egs.link
        } else {
            clone.querySelector('.egs').remove()
        }

        // INFO GOG
        if (data.gog !== null){
            clone.querySelector('.titulo').innerHTML = data.gog.nombre;

            // VERIFICAR DESCRIPCION
            if (clone.querySelector('.descripcion').innerText.trim() === 'descripcion') {
                clone.querySelector('.descripcion').innerHTML = data.gog.descripcion;
            }

            // VERIFICAR COVER
            if (clone.querySelector('img').src === ''){
                clone.querySelector('img').src = data.gog.img;
                clone.querySelector('img').style.minHeight = '500px';
            }

            // PRECIOS
            clone.querySelector('.gog .precio').innerText = `${data.gog.precio}$`;
            if (data.gog.descuento !== null){
                const porcentaje = 100 - ((data.gog.descuento * 100) / data.gog.precio);
                clone.querySelector('.gog .descuento').innerText = `${porcentaje.toFixed(2)}%`
                clone.querySelector('.gog .final').innerText = `${data.gog.descuento}$`;
            } else{
                clone.querySelector('.gog .descuento').innerText = 'Ninguno';
                clone.querySelector('.gog .final').innerText = `${data.gog.precio}$`;
            }

            clone.querySelector('.gog a').href = data.gog.link   
        } else {
            clone.querySelector('.gog').remove()
        }

        // EN CASO DE NO HABER DATOS
        if ((data.steam === null) && (data.gog === null) && (data.egs === null)){
            modalContent.innerHTML = '';
            modalContent.innerHTML = "<h1 align='center'> No se encontraron datos! </h1>";
        } else{
            modalContent.innerHTML = '';
            modalContent.appendChild(clone);
        }
    }
</script>
{% endblock %}

src/templates/ofertas.html
{% extends 'base.html' %}

{% block head%} 
{{ super() }}
<link rel="stylesheet" href="{{url_for('static', filename='css/ofertas.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='css/responsive.css')}}">
{% endblock %}

{% block title %} Ofertas {% endblock %}

{% block main %}
<h2>Ofertas de steam</h2>
<div class="ofertas-steam">
    <div class="loading w-100 text-center">
        <div class="spinner-border text-primary" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>
</div>
<a class="btn btn-success mb-2 d-none btn-steam" target="_blank" href="https://store.steampowered.com/search/?category1=998&os=win&specials=1&ndl=1"> Ver más en steam... </a>

<h2>Ofertas de Epic Games</h2>
<div class="ofertas-egs">
    <div class="loading w-100 text-center">
        <div class="spinner-border text-primary" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>
</div>
<a class="btn btn-success mb-2 d-none btn-egs" target="_blank" href="https://store.epicgames.com/es-ES/browse?sortBy=releaseDate&sortDir=DESC&tag=Superoferta%20de%20Epic&category=Game&count=40&start=0"> Ver más en Epic Games... </a>

<h2>Ofertas de GOG</h2>
<div class="ofertas-gog">
    <div class="loading w-100 text-center">
        <div class="spinner-border text-primary" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>
</div>
<a class="btn btn-success mb-2 d-none btn-gog" target="_blank" href="https://www.gog.com/en/games?discounted=true"> Ver más en gog... </a>

<template class="oferta-template">
    <div class="oferta">
        <div class="img">
            <img src="https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1551360/header.jpg?t=1717876415" alt="steam-img">
        </div>
        <div class="content">
            <div class="info">
                <h3 class="nombre"> Forza Horizon 5 <span class="descuento"> -50% </span> </h3>
                <div class="container-price">
                    <p><span class="precio"> 15$ </span></p>
                    <p><span class="final"> 7.5$ </span></p>
                </div>
            </div>
            <a href="" target="_blank" class="btn btn-success link"> <span class="material-symbols-outlined">arrow_forward</span></a>
        </div>
    </div>
</template>

<script src="{{url_for('static', filename='js/ofertas.js')}}"></script>

{% endblock %}

src/templates/partials/footer.html
<footer class="bg-dark">
    <p> Este sitio web fue creado con objetivo didactico y educativo, puedes acceder al repositorio o contactarme en los siguientes enlaces</p>
    <div class="contacto">
        <a href="https://github.com/Axforzi"><i class="fa-brands fa-github"></i></a>
        <a href="mailto:garcia.maikelr@gmail.com"><i class="fa-regular fa-envelope"></i></a>
        <a href="https://www.linkedin.com/in/maikel-garcía-8a3b60232/"><i class="fa-brands fa-linkedin"></i></a>
    </div>
</footer>

src/templates/partials/header.html
<header>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">
                <h3><img src="{{ url_for('static', filename='img/comparacion.svg')}}" alt=""></h3>
            </a>
            <button class="navbar-toggler shadow-none" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{{ url_for('index.get_index') }}" class="nav-link {{ 'active' if url_for('index.get_index') == url_for(request.endpoint) else ''}}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if url_for('index.get_ofertas') == url_for(request.endpoint) else ''}}" href="{{ url_for('index.get_ofertas') }}">Ofertas de hoy!</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>